services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=${APP_TIMEZONE}
  app:
    image: app
    restart: always
    env_file:
      - .env
    environment:
      - TZ=${APP_TIMEZONE}
    user: "www-data:www-data"
  nginx:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    environment:
      - TZ=${APP_TIMEZONE}
